{{- if global.deploymentHooks.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panoptica-kubernetes-integration.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panoptica-kubernetes-integration.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
type: panoptica.app/release
data:
  chartValues: {{ toYaml $.Values | b64enc }}
  chartVersion: {{ .Chart.Version }}
  deploymentStatus: "installing"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panoptica-kubernetes-integration.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panoptica-kubernetes-integration.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
type: panoptica.app/release
data:
  chartValues: {{ toYaml $.Values | b64enc }}
  chartVersion: {{ .Chart.Version }}
  deploymentStatus: "deployed"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panoptica-kubernetes-integration.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panoptica-kubernetes-integration.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: SyncFail
type: panoptica.app/release
data:
  chartValues: {{ toYaml $.Values | b64enc }}
  chartVersion: {{ .Chart.Version }}
  deploymentStatus: "failed"
---
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panoptica-kubernetes-integration.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panoptica-kubernetes-integration.labels" . | nindent 4 }}
type: panoptica.app/release
data:
  chartValues: {{ toYaml $.Values | b64enc }}
  chartVersion: {{ .Chart.Version }}
  deploymentStatus: "untrackable"
  deploymentStatusMessage: "xxxxx"
{{- end }}
